export enum DIToken {
    CREATE_USER_USE_CASE = 'CREATE_USER_USE_CASE',
    GET_ONE_USER_USE_CASE = 'GET_ONE_USER_USE_CASE',
    LOGIN_USE_CASE = 'LOGIN_USE_CASE',
    GOOGLE_LOGIN_USE_CASE = 'GOOGLE_LOGIN_USE_CASE',

    USER_REPOSITORY = 'USER_REPOSITORY',

    QUEUE_SERVICE = 'QUEUE_SERVICE',
    TOKEN_SERVICE = 'TOKEN_SERVICE',
    HASH_SERVICE = 'HASH_SERVICE',
}
