import { BadRequestException } from '@nestjs/common';
import { AggregateRoot, UUID } from '../core/aggregate-root.base';
import { MESSAGE_CONTENT_MAX_LENGTH } from './message.constants';
import { MessageSentEvent } from './events/message-sent.event';

interface MessageProps {
    conversationId: UUID;
    senderId: UUID;
    content: string;
    attachmentKeys: string[];
    serverTs: Date;
}

/**
 * `messageId` is generated by the CLIENT (UUID v7) and threaded through the
 * gateway → Kafka → consumer. The consumer uses it as the Mongo `_id`, which
 * gives at-least-once delivery + idempotent insert. Retries with the same
 * messageId collide on the unique `_id` index and are treated as no-ops.
 */
export interface SendMessageInput {
    messageId: UUID;
    conversationId: UUID;
    senderId: UUID;
    content: string;
    attachmentKeys?: string[];
}

export interface ReconstituteMessageProps {
    id: UUID;
    conversationId: UUID;
    senderId: UUID;
    content: string;
    attachmentKeys: string[];
    serverTs: Date;
}

/**
 * Message aggregate root.
 *
 * Sibling aggregate to Conversation — references it only by `conversationId`.
 * The conversation enforces membership; this aggregate enforces content
 * invariants and immutability of the ordering signal `serverTs`.
 *
 * Identity is UUIDv7 (time-ordered) so that the `_id` index gives a useful
 * approximate-time sort even if `serverTs` is unavailable, and writes
 * cluster on the right edge of the B-tree.
 *
 * Composition invariant: a message must carry content OR at least one
 * attachment. Asset references are stored as opaque object-storage keys
 * (`attachmentKeys`) — the asset bounded context owns type detection,
 * variant generation, and lifecycle. This aggregate treats them as strings.
 */
export class MessageEntity extends AggregateRoot<MessageProps> {
    private constructor(props: MessageProps, id: UUID) {
        super(props, id);
        // serverTs is the canonical timestamp; collapse base-class createdAt/updatedAt onto it.
        this.setTimestamps(props.serverTs, props.serverTs);
    }

    /**
     * Factory for a newly-sent message. `serverTs` is supplied by the
     * application service via the injected `IClock`, never by the
     * domain layer or the client.
     */
    static send(input: SendMessageInput, serverTs: Date): MessageEntity {
        const content = input.content.trim();
        const attachmentKeys = input.attachmentKeys ?? [];

        MessageEntity.validateComposition({ content, attachmentKeys });

        if (content.length > MESSAGE_CONTENT_MAX_LENGTH) {
            throw new BadRequestException(
                `Message content cannot exceed ${MESSAGE_CONTENT_MAX_LENGTH} characters`,
            );
        }

        const message = new MessageEntity(
            {
                conversationId: input.conversationId,
                senderId: input.senderId,
                content,
                attachmentKeys,
                serverTs,
            },
            input.messageId,
        );

        message.addDomainEvent(
            new MessageSentEvent(
                input.messageId,
                input.conversationId,
                input.senderId,
                content,
                attachmentKeys,
                serverTs,
            ),
        );

        return message;
    }

    static reconstitute(props: ReconstituteMessageProps): MessageEntity {
        return new MessageEntity(
            {
                conversationId: props.conversationId,
                senderId: props.senderId,
                content: props.content,
                attachmentKeys: props.attachmentKeys,
                serverTs: props.serverTs,
            },
            props.id,
        );
    }

    /**
     * A valid message must carry at least one of: content, attachments.
     * Empty messages are rejected at the boundary, not silently persisted.
     */
    private static validateComposition(input: {
        content: string;
        attachmentKeys: string[];
    }): void {
        const hasContent = input.content.length > 0;
        const hasAttachments = input.attachmentKeys.length > 0;

        if (!hasContent && !hasAttachments) {
            throw new BadRequestException(
                'Message must have content or attachments',
            );
        }
    }

    get conversationId(): UUID {
        return this._props.conversationId;
    }

    get senderId(): UUID {
        return this._props.senderId;
    }

    get content(): string {
        return this._props.content;
    }

    get attachmentKeys(): string[] {
        return [...this._props.attachmentKeys];
    }

    get serverTs(): Date {
        return this._props.serverTs;
    }
}
